# Generated by Django 3.0.9 on 2020-10-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsgroups',
            name='glevel',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='سطح گروه'),
        ),
        migrations.AlterField(
            model_name='productsgroups',
            name='gparentid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کد گروه سطح بالاتر'),
        ),
        migrations.DeleteModel(
            name='Group_Detail',
        ),
    ]
