# Generated by Django 3.0.9 on 2020-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_auto_20201010_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='centercontactus',
            name='fax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس'),
        ),
        migrations.AddField(
            model_name='centercontactus',
            name='mobile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AddField(
            model_name='centercontactus',
            name='tell2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن دوم شرکت'),
        ),
        migrations.AddField(
            model_name='salecontactus',
            name='sfax',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس'),
        ),
        migrations.AddField(
            model_name='salecontactus',
            name='smobile',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن همراه'),
        ),
        migrations.AddField(
            model_name='salecontactus',
            name='stell2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن دوم شرکت'),
        ),
    ]
