# Generated by Django 3.0.9 on 2020-10-13 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_auto_20201013_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstpagelogo',
            old_name='logo',
            new_name='Logo',
        ),
    ]
