# Generated by Django 3.0.9 on 2020-10-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_auto_20201013_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='viewcounter',
        ),
    ]
