# Generated by Django 3.0.9 on 2020-10-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0006_remove_products_viewcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercontactus',
            name='ltworkend',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت پایان کار در پنج شنبه'),
        ),
        migrations.AlterField(
            model_name='centercontactus',
            name='ltworkstart',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت شروع کار در پنج شنبه'),
        ),
        migrations.AlterField(
            model_name='centercontactus',
            name='wtworkend',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت پایان کار در هفته'),
        ),
        migrations.AlterField(
            model_name='centercontactus',
            name='wtworkstart',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت شروع کار در هفته'),
        ),
        migrations.AlterField(
            model_name='salecontactus',
            name='sltworkend',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت پایان کار در پنج شنبه'),
        ),
        migrations.AlterField(
            model_name='salecontactus',
            name='sltworkstart',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت شروع کار در پنج شنبه'),
        ),
        migrations.AlterField(
            model_name='salecontactus',
            name='swtworkend',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت پایان کار در هفته'),
        ),
        migrations.AlterField(
            model_name='salecontactus',
            name='swtworkstart',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ساعت شروع کار در هفته'),
        ),
    ]
