# Generated by Django 3.0.9 on 2020-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0007_auto_20201015_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparticle',
            name='ATotal',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='جمع کل'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='Amount',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='AuxAmount',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='مقدار فرعی'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='FPId',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='دوره مالی'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='Id2',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='کد فاکتور انتقالی'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='MerchandiseId',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='Percentage',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='SPADesc',
            field=models.CharField(blank=True, default=0, max_length=1024, null=True, verbose_name='شرح آرتیکل'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='SPId',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='کد فاکتور'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='UnitId',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='کد کالا'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='UnitPrice',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='VCharge',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='عوارض'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='VTax',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='مالیات'),
        ),
    ]
