# Generated by Django 3.0.9 on 2020-10-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0009_auto_20201020_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparticle',
            name='ATotal',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True, verbose_name='جمع کل'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='Amount',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='Percentage',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='UnitPrice',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='VCharge',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True, verbose_name='عوارض'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='VTax',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True, verbose_name='مالیات'),
        ),
    ]
