# Generated by Django 3.0.9 on 2020-10-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0011_auto_20201020_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='parametrs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ersal', models.CharField(max_length=1000, verbose_name='روش ارسال')),
                ('osool', models.CharField(max_length=1000, verbose_name='خط مشی')),
            ],
            options={
                'verbose_name': 'پارامتر',
                'verbose_name_plural': 'پارامتر ها',
                'db_table': 'parametrs',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='ATotal',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='جمع کل'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='Percentage',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='UnitPrice',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='VCharge',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='عوارض'),
        ),
        migrations.AlterField(
            model_name='sparticle',
            name='VTax',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مالیات'),
        ),
    ]
