# Generated by Django 3.0.9 on 2020-10-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0012_auto_20201021_1959'),
    ]

    operations = [
 
    ]
