# Generated by Django 3.0.9 on 2020-10-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0015_auto_20201022_1813'),
    ]

    operations = [
       
    ]
