# Generated by Django 3.0.9 on 2020-10-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0017_auto_20201024_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalcheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalprise', models.IntegerField(blank=True, default=0, null=True, verbose_name='مبلغ پرداخت شده')),
                ('Bankreceipt', models.IntegerField(blank=True, default=0, null=True, verbose_name='شماره فیش بانکی')),
                ('TrackingCode', models.IntegerField(blank=True, default=0, null=True, verbose_name='کد رهگیری')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'بررسی پرداخت',
                'verbose_name_plural': 'بررسی های پرداخت ها',
                'db_table': 'finalcheckout',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),

    ]
