# Generated by Django 3.0.9 on 2020-10-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0019_auto_20201025_2223'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='lastnews',
            name='newsimg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس خبر'),
        ),
       
    ]
