# Generated by Django 3.0.9 on 2020-10-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0020_auto_20201025_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastnews',
            name='khdesc',
            field=models.CharField(default='NULL', max_length=200, verbose_name='حلاصه شرح'),
            preserve_default=False,
        ),
       
    ]
