# Generated by Django 3.0.9 on 2020-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0021_auto_20201025_1731'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='firstpagebaners',
            name='baner6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='(پایین صفحه)بنر شش'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='baner7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر هفت(پایین صفحه)'),
        ),
        
        migrations.AlterField(
            model_name='lastnews',
            name='khdesc',
            field=models.CharField(max_length=200, verbose_name='خلاصه شرح'),
        ),
    ]
