# Generated by Django 3.0.9 on 2020-10-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0022_auto_20201026_1856'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='productsgroups',
            name='Group_Desc_1',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیح گروه بالای صفحه جزئیات'),
        ),
        migrations.AddField(
            model_name='productsgroups',
            name='Group_Desc_2',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیح گروه پایین صفحه جزئیات'),
        ),
        migrations.AddField(
            model_name='productsgroups',
            name='Group_Desc_3',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیح گروه پایین صفحه جزئیات'),
        ),
        migrations.AddField(
            model_name='productsgroups',
            name='Group_Desc_4',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیح گروه پایین صفحه جزئیات'),
        ),
        migrations.AddField(
            model_name='productsgroups',
            name='group_img_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس گروه کالا بالای صفحه جزئیات'),
        ),
        migrations.AddField(
            model_name='productsgroups',
            name='group_img_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس گروه کالا پایین صفحه جزئیات'),
        ),
        migrations.AddField(
            model_name='productsgroups',
            name='group_img_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس گروه کالا پایین صفحه جزئیات'),
        ),
        migrations.AddField(
            model_name='productsgroups',
            name='group_img_4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس گروه کالا پایین صفحه جزئیات'),
        ),
    ]
