# Generated by Django 3.0.9 on 2020-10-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0023_auto_20201028_0059'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='productsgroups',
            name='Group_Desc_2',
        ),
        migrations.RemoveField(
            model_name='productsgroups',
            name='Group_Desc_3',
        ),
        migrations.RemoveField(
            model_name='productsgroups',
            name='Group_Desc_4',
        ),
        migrations.RemoveField(
            model_name='productsgroups',
            name='group_img_2',
        ),
        migrations.RemoveField(
            model_name='productsgroups',
            name='group_img_3',
        ),
        migrations.RemoveField(
            model_name='productsgroups',
            name='group_img_4',
        ),
       
    ]
