# Generated by Django 3.0.9 on 2020-10-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0025_auto_20201028_0237'),
    ]

    operations = [

        
        migrations.AlterField(
            model_name='products',
            name='desc_1',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='درباره محصول شرح 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc_2',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='درباره محصول شرح 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='desc_3',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیحات محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_desc_1',
            field=models.ImageField(upload_to='', verbose_name=' عکس شرح 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_desc_2',
            field=models.ImageField(upload_to='', verbose_name='عکس شرح 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_desc_3',
            field=models.ImageField(upload_to='', verbose_name='عکس توضیحات محصول'),
        ),
    ]
