# Generated by Django 3.0.9 on 2020-10-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0026_auto_20201029_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='parametsaccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=1000, verbose_name='حساب')),
                ('accountimg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس بانک')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'حساب ها',
                'db_table': 'parametsaccounts',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='parametssas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=4000, verbose_name='شرح')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس ')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'خدمات پس از فروش',
                'verbose_name_plural': 'خدمات های پس از فروش',
                'db_table': 'parametssas',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='parametssupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('desc', models.TextField(max_length=4000, verbose_name='شرح')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس ')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'خدمات پس از فروش',
                'verbose_name_plural': 'خدمات های پس از فروش',
                'db_table': 'parametssupport',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
       
        migrations.AddField(
            model_name='centercontactus',
            name='internetimg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=' (پایین صفحه)عکس خدمات اینترنتی'),
        ),
        migrations.AddField(
            model_name='centercontactus',
            name='internetsaledesc',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیح خدمات اینترنتی (پایین صفحه))'),
        ),
        migrations.AddField(
            model_name='centercontactus',
            name='internetsaletitle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان خدمات اینترنتی (پایین صفحه)'),
        ),
        
    ]
