# Generated by Django 3.0.9 on 2020-11-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0027_auto_20201029_0822'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='firstpagebaners',
            name='baner10',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 10'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='baner11',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 11'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='baner8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 8'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='baner9',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 9'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group1', to='WebSite.productsgroups', verbose_name='گروه بنر 1'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group10', to='WebSite.productsgroups', verbose_name='گروه بنر 10'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group11', to='WebSite.productsgroups', verbose_name='گروه بنر 11'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group2', to='WebSite.productsgroups', verbose_name='گروه بنر 2'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group3', to='WebSite.productsgroups', verbose_name='گروه بنر 3'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group4', to='WebSite.productsgroups', verbose_name='گروه بنر 4'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group5', to='WebSite.productsgroups', verbose_name='گروه بنر 5'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group6', to='WebSite.productsgroups', verbose_name='گروه بنر 6'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group7', to='WebSite.productsgroups', verbose_name='گروه بنر 7'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group8', to='WebSite.productsgroups', verbose_name='گروه بنر 8'),
        ),
        migrations.AddField(
            model_name='firstpagebaners',
            name='group9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group9', to='WebSite.productsgroups', verbose_name='گروه بنر 9'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='baner1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 1'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='baner2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 2'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='baner3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 3'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='baner4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 4'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='baner5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='بنر 5'),
        ),
    ]
