# Generated by Django 3.0.9 on 2020-11-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0028_auto_20201102_1013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parametrs',
        ),
        migrations.AddField(
            model_name='parametrsersal',
            name='Create_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parametrsersal',
            name='Create_Uid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='parametrsersal',
            name='Update_Date',
            field=models.DateTimeField(auto_now_add=True, default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parametrsersal',
            name='Update_Uid',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده'),
        ),
        migrations.AlterField(
            model_name='centercontactus',
            name='internetimg',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس خدمات اینترنتی (پایین صفحه)'),
        ),
        migrations.AlterField(
            model_name='centercontactus',
            name='internetsaledesc',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='توضیح خدمات اینترنتی (پایین صفحه)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_desc_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=' عکس شرح 1'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_desc_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس شرح 2'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_desc_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس توضیحات محصول'),
        ),
    ]
