# Generated by Django 3.0.9 on 2020-11-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0029_auto_20201102_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='priceoff',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت محصول پس از تخفیف'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='priceorg',
            field=models.BigIntegerField(verbose_name='قیمت محصول'),
        ),
    ]
