# Generated by Django 3.0.9 on 2020-11-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0031_auto_20201104_2121'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productscategory',
            table='productscategory',
        ),
    ]
