# Generated by Django 3.0.9 on 2020-11-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0032_auto_20201106_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='priceorg',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='قیمت محصول'),
        ),
    ]
