# Generated by Django 3.0.9 on 2020-11-06 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0034_auto_20201106_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='commentdetails',
            name='cid',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.comment', verbose_name='کد کامنت'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group1', to='WebSite.productsgroups', verbose_name='گروه بنر 1'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group10', to='WebSite.productsgroups', verbose_name='گروه بنر 10'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group11', to='WebSite.productsgroups', verbose_name='گروه بنر 11'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group2', to='WebSite.productsgroups', verbose_name='گروه بنر 2'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group3', to='WebSite.productsgroups', verbose_name='گروه بنر 3'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group4', to='WebSite.productsgroups', verbose_name='گروه بنر 4'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group5', to='WebSite.productsgroups', verbose_name='گروه بنر 5'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group6', to='WebSite.productsgroups', verbose_name='گروه بنر 6'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group7', to='WebSite.productsgroups', verbose_name='گروه بنر 7'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group8', to='WebSite.productsgroups', verbose_name='گروه بنر 8'),
        ),
        migrations.AlterField(
            model_name='firstpagebaners',
            name='group9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group9', to='WebSite.productsgroups', verbose_name='گروه بنر 9'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productsbrands', verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='products',
            name='group',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.productsgroups', verbose_name='نام گروه'),
        ),
        migrations.AlterField(
            model_name='sellbascket',
            name='pid',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.PROTECT, to='WebSite.products', verbose_name='کد محصول'),
        ),
    ]
