# Generated by Django 3.0.9 on 2020-11-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0035_auto_20201106_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='guarantee',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='گارانتی'),
        ),
        migrations.AddField(
            model_name='products',
            name='supportaftersale',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='خدمات پس از فروش'),
        ),
    ]
