# Generated by Django 3.0.9 on 2020-11-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0036_auto_20201108_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='guaranteecount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مدت گارانتی (به سال)'),
        ),
        migrations.AddField(
            model_name='products',
            name='supportaftersalecount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='مدت خدمات پس از فروش (به سال)'),
        ),
    ]
