# Generated by Django 3.0.9 on 2020-11-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0039_auto_20201111_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsgroups',
            name='group_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس گروه کالا'),
        ),
    ]
