# Generated by Django 3.0.9 on 2020-11-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0040_auto_20201111_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerquestions',
            name='tell',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن'),
        ),
    ]
