# Generated by Django 3.0.9 on 2020-11-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0042_sparticle_merchandisename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparticle',
            name='UnitId',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='واحد شمارش'),
        ),
    ]
