# Generated by Django 3.0.9 on 2020-12-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0044_weblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id2', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='کد چک انتقالی')),
                ('CheckNo', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='شماره چک ')),
                ('CValue', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='مبلغ')),
                ('PayerFAccId', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام پرداخت کننده')),
                ('CDate', models.CharField(blank=True, default=0, max_length=1024, null=True, verbose_name='تاریخ چک')),
                ('RcptDate', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='تاریخ سررسید')),
                ('VDate', models.CharField(blank=True, default=0, max_length=1024, null=True, verbose_name='تاریخ')),
                ('CStatus', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='وضعیت چک')),
                ('CType', models.CharField(blank=True, default=0, max_length=1024, null=True, verbose_name='وضعیت یک')),
                ('SType', models.CharField(blank=True, default=0, max_length=1024, null=True, verbose_name='وضعیت دو')),
                ('CId', models.CharField(blank=True, default=0, max_length=1024, null=True, verbose_name='وضعیت دو')),
            ],
            options={
                'verbose_name': 'ریز رسید ',
                'verbose_name_plural': 'ریز رسید ها',
                'db_table': 'Check',
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='PayRcv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PNo', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='شماره رسید')),
                ('PayType', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نوع رسید')),
                ('PDate', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='تاریخ رسید')),
                ('RcvrFAccId', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('PDesc', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='شرح رسید')),
                ('CustomerId', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام مشتری')),
                ('PCValue', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='مبلغ')),
            ],
            options={
                'verbose_name': 'رسید',
                'verbose_name_plural': 'رسید ها',
                'db_table': 'PayRcv',
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='PayRcvCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CheckId', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='کد چک')),
                ('PayRcvId', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='کد رسید')),
            ],
            options={
                'verbose_name': 'میانی',
                'verbose_name_plural': 'میانی ها',
                'db_table': 'PayRcvCheck',
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
    ]
