# Generated by Django 3.0.9 on 2020-12-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0046_payrcv_scommit'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='numberofgoods',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تعداد کالا'),
        ),
    ]
