# Generated by Django 3.0.9 on 2020-12-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0047_products_numberofgoods'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='goods',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='موجودی'),
        ),
    ]
