# Generated by Django 3.0.9 on 2020-12-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0048_products_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='goods',
            field=models.BooleanField(default=0, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='products',
            name='numberofgoods',
            field=models.IntegerField(default=0, verbose_name='تعداد کالا'),
        ),
    ]
