# Generated by Django 3.0.9 on 2020-09-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_auto_20200910_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centercontactus',
            name='tell',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن شرکت'),
        ),
        migrations.AlterField(
            model_name='salecontactus',
            name='stell',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تلفن دفتر'),
        ),
    ]
