# Generated by Django 3.0.9 on 2020-09-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_auto_20200910_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutusp1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whoweare', models.CharField(blank=True, max_length=2000, null=True, verbose_name='ما که هستیم')),
                ('teamimg', models.ImageField(upload_to='', verbose_name='عکس گروه')),
                ('Create_Date', models.DateTimeField(auto_now=True)),
                ('Update_Date', models.DateTimeField(auto_now_add=True)),
                ('Create_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ایجاد کننده')),
                ('Update_Uid', models.IntegerField(blank=True, default=0, null=True, verbose_name='کاربر ویرایش کننده')),
            ],
            options={
                'verbose_name': 'درباره ما بخش اول',
                'verbose_name_plural': 'درباره ما ها بخش اول',
                'db_table': 'aboutusp1',
                'ordering': ['id'],
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='personelimg',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='whoweare',
        ),
    ]
