# Generated by Django 3.0.9 on 2020-09-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0006_auto_20200910_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='personelimg',
            field=models.ImageField(default='null', upload_to='', verbose_name='عکس گروه'),
            preserve_default=False,
        ),
    ]
