# Generated by Django 3.0.9 on 2020-09-10 17:56

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0007_aboutus_personelimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField(default=0, verbose_name='کد مشتری')),
                ('Name', models.IntegerField(default=0, verbose_name='نام')),
                ('Family', models.IntegerField(blank=True, default=0, null=True, verbose_name='نام خانوادگی')),
                ('CellPhone', models.IntegerField(default=0, verbose_name='تلفن همراه')),
                ('PhoneNo', models.IntegerField(default=0, verbose_name='تلفن ثابت')),
                ('FaxNo', models.IntegerField(default=0, verbose_name='شماره فکس')),
                ('SCode', models.IntegerField(default=0, verbose_name='کد اشتراک')),
                ('Email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('EcCode', models.CharField(max_length=1000, verbose_name='کد اقتصادی')),
                ('Address', models.CharField(max_length=1000, verbose_name='آدرس')),
                ('ZipCode', models.IntegerField(default=0, verbose_name='کد پستی')),
                ('LRes', models.IntegerField(default=0, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتری ها',
                'db_table': 'Customers',
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.CreateModel(
            name='SpFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FactorNo', models.IntegerField(default=0, verbose_name='شماره فاکتور')),
                ('FactorType', models.IntegerField(default=0, verbose_name='نوع فاکتور')),
                ('CustomerId', models.IntegerField(default=0, verbose_name='نوع فاکتور')),
                ('Total', models.IntegerField(default=0, verbose_name='نوع فاکتور')),
                ('Discount', models.IntegerField(default=0, verbose_name='نوع فاکتور')),
                ('Expense', models.IntegerField(default=0, verbose_name='نوع فاکتور')),
                ('EDate', django_jalali.db.models.jDateField(default='1900-01-01', verbose_name='تاریخ فاکتور')),
                ('SPDesc', models.CharField(max_length=1000, verbose_name='نوع فاکتور')),
            ],
            options={
                'verbose_name': 'فاکتور ورودی',
                'verbose_name_plural': 'فاکتور های وردی',
                'db_table': 'SpFactor',
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
    ]
