# Generated by Django 3.0.9 on 2020-09-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0009_auto_20200910_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpFactor',
        ),
    ]
