# Generated by Django 3.0.9 on 2020-09-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0010_delete_spfactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='cid',
        ),
    ]
