# Generated by Django 3.0.9 on 2020-09-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0011_remove_customers_cid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='CellPhone',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='EcCode',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='FaxNo',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='LRes',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='PhoneNo',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='SCode',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='ZipCode',
        ),
    ]
