# Generated by Django 3.0.9 on 2020-09-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0012_auto_20200910_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsgroups',
            name='group_img',
            field=models.ImageField(default='null', upload_to='', verbose_name='عکس گروه کالا'),
            preserve_default=False,
        ),
    ]
