# Generated by Django 3.0.9 on 2020-09-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0013_productsgroups_group_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbascket',
            name='pcount',
            field=models.IntegerField(default=0, verbose_name='تعداد کالا'),
        ),
    ]
