# Generated by Django 3.0.9 on 2020-09-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0014_sellbascket_pcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellbascket',
            name='pdiscount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='تخیف کالا'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='pexpense',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='هزینه کالا'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='pprise',
            field=models.IntegerField(default=0, verbose_name='قیمت کالا'),
        ),
        migrations.AddField(
            model_name='sellbascket',
            name='ptotal',
            field=models.IntegerField(default=0, verbose_name='جمع کل کالا'),
        ),
    ]
