# Generated by Django 3.0.9 on 2020-09-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0015_auto_20200911_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Head',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='تیتر'),
        ),
    ]
