# Generated by Django 3.0.9 on 2020-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0018_auto_20200917_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellbascket',
            name='pexpense',
        ),
        migrations.RemoveField(
            model_name='sellbascket',
            name='ptotal',
        ),
        migrations.AddField(
            model_name='customers',
            name='Address',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='CSex',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='CellPhone',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='EcCode',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='Email',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='FAccId',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='FPId',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='FaxNo',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='PhoneNo',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='SCode',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='TRes',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='UserId',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='customers',
            name='ZipCode',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Family',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Name',
            field=models.CharField(default=0, max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='sellbascket',
            name='pcount',
            field=models.IntegerField(default=1, verbose_name='تعداد کالا'),
        ),
    ]
