# Generated by Django 3.0.9 on 2020-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0020_sparticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparticle',
            name='SPADesc',
            field=models.CharField(default=0, max_length=1024, verbose_name='نام'),
        ),
    ]
