# Generated by Django 3.0.9 on 2020-09-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0022_auto_20200919_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FactorNo', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('ReferenceNo', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('SPDate', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('FactorType', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام خانوادگی')),
                ('CustomerId', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('Total', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('Discount', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('Expense', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('SPDesc', models.CharField(blank=True, default=0, max_length=1024, null=True, verbose_name='نام')),
                ('CustomerName', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('CustomerPhoneNo', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('CustomerEcCode', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('CustomerAddress', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('FPId', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('SC', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('FStatus', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('FactorSubType', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
                ('Committed', models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتور ها',
                'db_table': 'SPFactor',
                'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')),
            },
        ),
        migrations.AlterModelOptions(
            name='sparticle',
            options={'permissions': (('can_read_private_section', 'administrator'), ('SubAdmin', 'SubAdmin'), ('user_watcher', 'User')), 'verbose_name': 'ریز فاکتور ', 'verbose_name_plural': 'ریز فاکتور ها'},
        ),
    ]
