# Generated by Django 3.0.9 on 2020-09-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0026_auto_20200927_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spfactor',
            name='Total',
            field=models.CharField(blank=True, default=0, max_length=200, null=True, verbose_name='نام'),
        ),
    ]
