# Generated by Django 3.0.9 on 2020-10-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0028_group_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsgroups',
            name='group_level',
            field=models.ImageField(default=0, upload_to='', verbose_name='سطح گروه'),
        ),
    ]
