# Generated by Django 3.0.9 on 2020-10-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0029_productsgroups_group_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsgroups',
            name='group_parentid',
            field=models.ImageField(default=0, upload_to='', verbose_name='کد گروه سطح بالاتر'),
        ),
    ]
